import Head from 'next/head'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'


export default function Home() {
  return (
    <div>
      <Head>
        <title>NEXT PRO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Next JS SPA Wep App' message='Next.js and Tailwaind CSS framework.' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
